language: node_js
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
notifications:
  slack:
      on_success: change
      on_failure: always
node_js:
  - 'node'
before_install:
  - npm i -g npm@latest
install:
  - npm install
before_script:
  - npm prune
after_success:
  - npx -p node@8 npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
