import TorrentLibrary from 'torrent-files-library';
import chalk from 'chalk';
import figlet from 'figlet';
import clear from 'clear-terminal';
import fs from 'fs';
import path from 'path';

import menu from '../components/menu';
import eventHandler from '../components/eventHandler';


const { log } = console;

export default {
  command: 'parseFile <source>',
  aliases: ['file', 'f'],
  describe: 'Parse an JSON file generated by this cli to reload the config',
  handler(argv) {
    clear();

    const json = JSON.parse(fs.readFileSync(
      path.resolve(argv.source)
      , 'utf8',
    ));

    // lib instance
    let libInstance = TorrentLibrary.createFromJSON(json);

    // handle events provided by libInstance
    eventHandler(libInstance);

    log(chalk.yellow(figlet.textSync(
      'TFL',
      { horizontalLayout: 'full' },
    )));
    menu(libInstance);
  },
};
